---
- hosts: all
  gather_facts: True
  become: yes
  tasks:
    - name: Add docker repo
      shell:
        cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: install docker-ce and docker-ce-cli
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Enable docker
      service:
        name: docker
        enabled: yes
    - name: add vagrant to docker group
      user:
        name: vagrant
        groups: docker
    - reboot: 
