---
- hosts: all
  gather_facts: True
  become: yes
  vars:
    base: https://github.com/docker/compose/releases/download/1.27.0
  tasks:
    - name: setting up variables
      shell: uname -s
      register: system

    - shell: uname -m
      register: machine

    - name: Add docker repo
      shell:
        cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: install docker-ce and docker-ce-cli
      yum:
        name: "{{ packages }}"
        disable_gpg_check: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Enable docker
      service:
        name: docker
        enabled: yes
    - name: add vagrant to docker group
      user:
        name: vagrant
        groups: docker
    - name: install docker-compose
      get_url:
        url: "{{ base }}/docker-compose-{{ system.stdout }}-{{ machine.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: "0755"
    - reboot:
