---
- hosts: all
  gather_facts: True
  become: yes
  tasks:
    - name: Install loosends
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - vim
          - net-tools
          - git

    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest
